### ISSUE TITLE
【疑问】有关函数栈帧-stack5.png

### ISSUE THREAD

**Issue by skyleaworlder** [acodercat/function-call-principle#1]
个人以为 `stack5.png` 的左图有些奇怪：

![stack5](https://image.coder.cat/stack5.png)

* 如果这里的 `initial` 指的是 **销毁栈帧** 这个操作之前的状态，那么 `bp` 至少不应该指向当前函数栈帧 `old bp` 之外的空间；
* 如果这里的 `initial` 指的是整个栈帧创建之前的状态，那么 `ret addr` 应该还没有创建，`sp` 也不应该指向它；

`stack5.png` 图上方文字描述为：“销毁时先把 `栈指针` (sp) 移动到此时 `栈基址` (bp) 的位置”，按照 `stack5.png` 的 `initial` 状态，那么 `sp` 应该直接指向图中 `bp` 指向的区域（根据上文，这里的 `bp` 或许指的是上一个函数的 `old bp`）

综上我认为 `stack5.png` 的左图有些奇怪。如果我阅读时理解出现偏差，还请大佬直接 `close` 该 `issue` 😢

**Comment by acodercat** [comment]
感谢的你提出问题，这里左边的图确实有问题，`initial`状态应该指向sp和bp都应该指向被调用者栈帧，然后开始整个销毁过程。

**Comment by acodercat** [comment]
图片已更新
